title: Dom Pod Smokami
email: kontakt@podsmokami.pl
description: "Apartamenty z widokami na Tatry, sauna, codzienne świeże bułeczki."
baseurl: "" # Pozostaw puste, jeśli strona jest w głównej domenie
url: "https://podsmokami.pl"
markdown: kramdown
theme: minima # Jekyll wymaga zdefiniowania motywu, ale my użyjemy własnego układu
exclude: [Gemfile, Gemfile.lock, node_modules]
